In [67]:
# basic imports
import numpy as np
import pandas as pd
from numpy.linalg import inv
import matplotlib.pyplot as plt

In [69]:
# Load the data as a pandas dataframe
df = pd.read_csv("dataexercise2.csv")

# Convert the dataframe to a numpy array (for easier manipulation)
arr = df.to_numpy()

In [70]:
# Define functions to calculate foundamental values
def calc_gradient(x, y, thetas):
    # Calculate the gradient of the log likelihood
	return -x.T @ np.exp(x @ thetas.T) + x.T @ y

def calc_hessian_inverse(x, thetas):
    # Calculate the hessian matrix of the log likelihood
    hess = -x.T @ np.diag(np.exp(x @ thetas.T)) @ x
    return np.linalg.inv(hess)

In [71]:
# Split the dataset
# first 4 columns are features (x matrix)
# last column is label (y vector)
x = arr[:, :-1]
y = arr[:, -1]

In [98]:
# Sample thetas from prior distribution
featNum = x.shape[1]
std0 = 4
thetas = np.random.multivariate_normal(np.zeros(featNum), std0**2*np.eye(featNum))

In [99]:
# Newton algorithm implementation
iters = 1000
e = 1e-6

for i in range(iters):
    grad = calc_gradient(x, y, thetas)
    hess_inv = calc_hessian_inverse(x, thetas)
    update = grad @ hess_inv
    if np.any(np.abs(update)) > e:
        thetas = thetas - update
    else:
        print("Converged after {} iterations".format(i + 1))
        break

# Calculate the gaussian distribution of thetas with Laplace approximation
mean = thetas
cov = -calc_hessian_inverse(x, thetas)
print(mean)
print(cov)

Converged in 36 iterations
[ 1.12777336  0.42858431  0.01512131 -0.05416601]
[[ 0.03140956 -0.00820031  0.00116572 -0.00139328]
 [-0.00820031  0.00305825 -0.00031134  0.00066138]
 [ 0.00116572 -0.00031134  0.0148073  -0.0014676 ]
 [-0.00139328  0.00066138 -0.0014676   0.01173136]]
